# Generated by Django 5.2.14 on 2026-06-29 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0002_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPiiPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label (e.g. "French SSN")', max_length=100)),
                ('regex', models.TextField(help_text='Python regex pattern (without delimiters)')),
                ('placeholder', models.CharField(default='{{CUSTOM}}', help_text='Replacement text, e.g. {{FR_SSN}}', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom PII Pattern',
                'verbose_name_plural': 'Custom PII Patterns',
                'ordering': ['name'],
            },
        ),
    ]
