# Generated by Django 5.2.14 on 2026-06-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0003_custompiipattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_training_before_project',
            field=models.BooleanField(default=False, help_text='When enabled, users must pass all required training modules before creating projects.'),
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short summary shown in module list')),
                ('content', models.TextField(help_text='Markdown content for the training module')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_required', models.BooleanField(default=True, help_text='Required modules must be passed before project creation (when toggle is on)')),
                ('is_published', models.BooleanField(default=True)),
                ('pass_threshold', models.IntegerField(default=80, help_text='Minimum score (%) to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Module',
                'verbose_name_plural': 'Training Modules',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(blank=True, help_text='Optional 4th option', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option letter', max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Shown after answering')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='studio_models.trainingmodule')),
            ],
            options={
                'verbose_name': 'Training Question',
                'verbose_name_plural': 'Training Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score percentage (0-100)')),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Question ID → selected answer')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_models.trainingmodule')),
            ],
            options={
                'verbose_name': 'Training Completion',
                'verbose_name_plural': 'Training Completions',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
