# Generated by Django 5.2.14 on 2026-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0004_sitesettings_require_training_before_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_domains_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, users can configure custom domains for their projects.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enabled_frameworks',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of enabled framework names. Empty/null = all enabled.', null=True),
        ),
    ]
