# Generated by Django 5.2.14 on 2026-07-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0005_sitesettings_custom_domains_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='openclaw_session_key',
            field=models.CharField(blank=True, default='', help_text='OpenClaw gateway session key for persistent subagent sessions', max_length=255),
        ),
    ]
