# Generated by Django 5.2.14 on 2026-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0006_add_openclaw_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='openclaw_wizard_enabled',
            field=models.BooleanField(default=False, help_text='Route all wizard sessions through the OpenClaw gateway agent instead of the custom LLM runner.'),
        ),
    ]
