# Generated by Django 5.2.14 on 2026-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0007_sitesettings_openclaw_wizard_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wizard_web_search_enabled',
            field=models.BooleanField(default=False, help_text='Allow the wizard agent to search the web. When enabled, the wizard can look up docs and solutions online.'),
        ),
    ]
