# Generated by Django 5.2.14 on 2026-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0008_sitesettings_wizard_web_search_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerkey',
            name='is_platform',
            field=models.BooleanField(default=False, help_text="Platform-shared key (e.g. Groq free tier). Users don't see their own."),
        ),
    ]
