# Generated by Django 5.2.14 on 2026-07-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0009_providerkey_is_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_personal_keys',
            field=models.BooleanField(default=True, help_text='Allow users to add their own LLM provider keys. Disable for enterprise installs where only platform keys are used.'),
        ),
    ]
