# Generated by Django 5.2.14 on 2026-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0011_sitesettings_semgrep_scan_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='figma_enabled',
            field=models.BooleanField(default=False, help_text='Show Figma integration in the UI. Enable only after Figma app review is approved.'),
        ),
    ]
