# Generated by Django 5.2.14 on 2026-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0012_figma_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='penpot_enabled',
            field=models.BooleanField(default=True, help_text='Show Penpot integration in the UI. Penpot is self-hosted and always available.'),
        ),
    ]
