# Generated by Django 5.2.14 on 2026-07-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0013_penpot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerkey',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra fields for multi-key providers (e.g. Predator client_id/client_secret)'),
        ),
        migrations.AlterField(
            model_name='providerkey',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='providerkey',
            name='provider',
            field=models.CharField(choices=[('zai', 'Z.ai'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('predator', 'Predator (vLLM)')], max_length=30),
        ),
    ]
