# Generated by Django 5.2.14 on 2026-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_models', '0014_predator_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='predator_chat_default',
            field=models.BooleanField(default=False, help_text='Generated projects use Predator (GPT-OSS-20B) for chat/AI features instead of third-party APIs.'),
        ),
    ]
