# Generated by Django 5.2.14 on 2026-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='risk_tier',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='ai_generated_code',
            field=models.BooleanField(default=True, help_text='Whether this project uses AI-generated code (NIST AI RMF disclosure)'),
        ),
    ]
