# Generated by Django 5.2.14 on 2026-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='form_api_key',
            field=models.CharField(blank=True, editable=False, help_text='API key for public form submissions', max_length=64),
        ),
    ]
