# Generated by Django 5.2.14 on 2026-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_formsubmission_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_as_demo',
            field=models.BooleanField(default=False, help_text='Show on the public demos page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp — null means active', null=True),
        ),
    ]
