# Generated by Django 5.2.14 on 2026-07-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_show_as_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_openclaw_agent',
            field=models.BooleanField(default=False, help_text='When true, wizard uses OpenClaw gateway subagent instead of custom LLM loop'),
        ),
    ]
