# Generated by Django 5.2.14 on 2026-07-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_company_directory_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='use_openclaw_agent',
        ),
    ]
