# Generated by Django 5.2.14 on 2026-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_use_openclaw_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('html', 'HTML'), ('vite_react', 'Vite React'), ('astro', 'Astro'), ('next_static', 'Next.js Static'), ('django', 'Django App'), ('supabase', 'React + Supabase'), ('firebase', 'React + Firebase')], default='html', max_length=32),
        ),
    ]
