# Generated by Django 5.2.14 on 2026-07-21 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_add_firebase_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_project',
            field=models.ForeignKey(blank=True, help_text="Paired project (e.g. frontend ↔ backend). Wizard includes this project's context when building.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='linked_project_role',
            field=models.CharField(blank=True, help_text='Role of THIS project in the link: "frontend" or "backend"', max_length=20),
        ),
    ]
