# Generated by Django 5.2.14 on 2026-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('html', 'HTML'), ('vite_react', 'Vite React'), ('astro', 'Astro'), ('next_static', 'Next.js Static'), ('django', 'Django App'), ('supabase', 'React + Supabase'), ('firebase', 'React + Firebase'), ('angular', 'Angular'), ('dotnet', '.NET (C#)')], default='html', max_length=32),
        ),
    ]
