# Generated by Django 5.2.14 on 2026-07-28 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_project_framework'),
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.BigIntegerField(help_text='Unix timestamp when access_token expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_connection', to='projects.project')),
            ],
        ),
    ]
