# Generated by Django 5.2.14 on 2026-07-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_project_framework'),
        ('public_api', '0002_hubspot_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubspotCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('domain', models.CharField(blank=True, default='', max_length=500)),
                ('industry', models.CharField(blank=True, default='', max_length=500)),
                ('lifecycle_stage', models.CharField(blank=True, default='', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_companies', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'hubspot_id')},
            },
        ),
        migrations.CreateModel(
            name='HubspotContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_name', models.CharField(blank=True, default='', max_length=500)),
                ('lifecycle_stage', models.CharField(blank=True, default='', max_length=100)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='public_api.hubspotcompany')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_contacts', to='projects.project')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('project', 'hubspot_id')},
            },
        ),
        migrations.CreateModel(
            name='HubspotTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('pipeline_stage', models.CharField(blank=True, default='', max_length=50)),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('sentiment_score', models.IntegerField(default=0)),
                ('sentiment_summary', models.CharField(blank=True, default='', max_length=500)),
                ('sentiment_flags', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('created_at_hubspot', models.DateTimeField(blank=True, null=True)),
                ('last_updated_hubspot', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='public_api.hubspotcompany')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_tickets', to='projects.project')),
            ],
            options={
                'ordering': ['-last_updated_hubspot'],
                'unique_together': {('project', 'hubspot_id')},
            },
        ),
    ]
