# Generated by Django 5.2.14 on 2026-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_hubspotcompany_hubspotcontact_hubspotticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotticket',
            name='ai_summary',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
