# Generated by Django 5.2.14 on 2026-07-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_project_framework'),
        ('public_api', '0004_hubspotticket_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('ticket_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0)),
                ('companies', models.JSONField(blank=True, default=list)),
                ('suggested_response', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_topics', to='projects.project')),
            ],
            options={
                'ordering': ['-ticket_count'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='hubspotticket',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='public_api.tickettopic'),
        ),
    ]
