# Generated by Django 5.2.14 on 2026-07-15 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalTaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2035)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one active year at a time for the calculator')),
                ('social_security_rate', models.DecimalField(decimal_places=5, default=0.062, help_text='Social Security tax rate (e.g. 0.062 = 6.2%)', max_digits=6)),
                ('social_security_wage_base', models.PositiveIntegerField(default=177000, help_text='Social Security wage base cap')),
                ('medicare_rate', models.DecimalField(decimal_places=5, default=0.0145, help_text='Medicare tax rate (e.g. 0.0145 = 1.45%)', max_digits=6)),
                ('additional_medicare_rate', models.DecimalField(decimal_places=5, default=0.009, help_text='Additional Medicare rate above threshold', max_digits=6)),
                ('additional_medicare_threshold_single', models.PositiveIntegerField(default=200000)),
                ('additional_medicare_threshold_mfj', models.PositiveIntegerField(default=250000)),
                ('additional_medicare_threshold_mfs', models.PositiveIntegerField(default=125000)),
                ('additional_medicare_threshold_hoh', models.PositiveIntegerField(default=200000)),
                ('standard_deduction_single', models.PositiveIntegerField(default=15000)),
                ('standard_deduction_married', models.PositiveIntegerField(default=30000)),
                ('standard_deduction_hoh', models.PositiveIntegerField(default=22500)),
                ('pub15t_deduction_single', models.PositiveIntegerField(default=8600, help_text='Line 1g deduction equivalent for standard schedule (single/MFS)')),
                ('pub15t_deduction_married', models.PositiveIntegerField(default=12900, help_text='Line 1g deduction equivalent for standard schedule (MFJ)')),
                ('note', models.TextField(blank=True, help_text='Optional notes about this tax year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Federal Tax Year',
                'verbose_name_plural': 'Federal Tax Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='FederalBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('income_single', 'Income Tax — Single'), ('income_married', 'Income Tax — MFJ'), ('income_hoh', 'Income Tax — HOH'), ('withholding_standard_single', 'Withholding Standard — Single/MFS'), ('withholding_standard_married', 'Withholding Standard — MFJ'), ('withholding_standard_hoh', 'Withholding Standard — HOH'), ('withholding_step2_single', 'Withholding Step 2 — Single/MFS'), ('withholding_step2_married', 'Withholding Step 2 — MFJ'), ('withholding_step2_hoh', 'Withholding Step 2 — HOH')], max_length=40)),
                ('min_amount', models.PositiveIntegerField(help_text='Lower bound of bracket (annual)')),
                ('max_amount', models.PositiveIntegerField(blank=True, help_text='Upper bound (null = no limit)', null=True)),
                ('rate', models.DecimalField(decimal_places=5, help_text='Tax rate (e.g. 0.22 = 22%)', max_digits=6)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tax_data.federaltaxyear')),
            ],
            options={
                'verbose_name': 'Federal Bracket',
                'verbose_name_plural': 'Federal Brackets',
                'ordering': ['tax_year', 'schedule', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='StateTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2035)])),
                ('state_code', models.CharField(help_text='2-letter USPS state code (e.g. CA, NY)', max_length=2)),
                ('state_name', models.CharField(max_length=50)),
                ('tax_type', models.CharField(choices=[('none', 'No Income Tax'), ('flat', 'Flat Rate'), ('progressive', 'Progressive Brackets')], default='progressive', max_length=12)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=5, help_text='Flat tax rate (e.g. 0.0495 = 4.95%). Only used when tax_type=flat.', max_digits=6, null=True)),
                ('standard_deduction_single', models.PositiveIntegerField(default=0)),
                ('standard_deduction_married', models.PositiveIntegerField(default=0)),
                ('standard_deduction_hoh', models.PositiveIntegerField(default=0)),
                ('personal_exemption_single', models.PositiveIntegerField(default=0)),
                ('personal_exemption_married', models.PositiveIntegerField(default=0)),
                ('personal_exemption_hoh', models.PositiveIntegerField(default=0)),
                ('dependent_exemption', models.PositiveIntegerField(default=0, help_text='Per-dependent exemption amount (e.g. $4,930 for SC)')),
                ('has_local_taxes', models.BooleanField(default=False)),
                ('local_tax_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text="Internal notes about this state's tax rules")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Tax Profile',
                'verbose_name_plural': 'State Tax Profiles',
                'ordering': ['year', 'state_code'],
                'unique_together': {('year', 'state_code')},
            },
        ),
        migrations.CreateModel(
            name='StateInsuranceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sdi', 'SDI/TDI'), ('pfml', 'PFML'), ('sui', 'SUI')], max_length=10)),
                ('name', models.CharField(help_text='Display name (e.g. "CA SDI + PFL")', max_length=50)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Employee rate (e.g. 0.013 = 1.3%)', max_digits=8)),
                ('wage_base', models.PositiveIntegerField(blank=True, help_text='Annual wage cap (null = no cap)', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_rates', to='tax_data.statetaxprofile')),
            ],
            options={
                'verbose_name': 'State Insurance Rate',
                'verbose_name_plural': 'State Insurance Rates',
                'ordering': ['profile', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StateBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_status', models.CharField(choices=[('single', 'Single/MFS'), ('married', 'MFJ'), ('head_of_household', 'HOH')], max_length=20)),
                ('min_amount', models.PositiveIntegerField(help_text='Lower bound of bracket (annual)')),
                ('max_amount', models.PositiveIntegerField(blank=True, help_text='Upper bound (null = no limit)', null=True)),
                ('rate', models.DecimalField(decimal_places=5, help_text='Tax rate (e.g. 0.06 = 6%)', max_digits=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tax_data.statetaxprofile')),
            ],
            options={
                'verbose_name': 'State Bracket',
                'verbose_name_plural': 'State Brackets',
                'ordering': ['profile', 'filing_status', 'min_amount'],
            },
        ),
    ]
