# Generated by Django 5.2.14 on 2026-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetaxprofile',
            name='default_allowances_hoh',
            field=models.PositiveIntegerField(default=0, help_text='Default allowances for head of household'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='default_allowances_married',
            field=models.PositiveIntegerField(default=0, help_text='Default allowances for married filing jointly'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='default_allowances_single',
            field=models.PositiveIntegerField(default=0, help_text='Default allowances for single/MFS filers (e.g. 1 for MN)'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='withholding_allowance_hoh',
            field=models.PositiveIntegerField(default=0, help_text='Per-allowance deduction amount for head of household filers'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='withholding_allowance_married',
            field=models.PositiveIntegerField(default=0, help_text='Per-allowance deduction amount for married filers'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='withholding_allowance_single',
            field=models.PositiveIntegerField(default=0, help_text='Per-allowance deduction amount for single filers (e.g. $4,950 for MN 2025)'),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='withholding_method',
            field=models.CharField(choices=[('standard_deduction', 'Standard Deduction'), ('allowance', 'Allowance-Based')], default='standard_deduction', help_text='How withholding is calculated: standard_deduction subtracts std ded + personal exemption from wages; allowance subtracts (default_allowances × allowance_amount) from wages.', max_length=20),
        ),
    ]
