# Generated by Django 5.2.14 on 2026-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0002_statetaxprofile_default_allowances_hoh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetaxprofile',
            name='allowance_includes_standard_deduction',
            field=models.BooleanField(default=True, help_text='True: allowance replaces standard deduction (MN-style, subtract only allowances×amount). False: both standard deduction and allowances are subtracted (GA-style).'),
        ),
    ]
