# Generated by Django 5.2.14 on 2026-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0004_add_source_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetaxprofile',
            name='last_verified',
            field=models.DateField(blank=True, help_text='Date when data was last verified against source', null=True),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='source_name',
            field=models.CharField(blank=True, default='', help_text='Name of the official source document', max_length=200),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Link to official state withholding publication'),
        ),
    ]
