# Generated by Django 5.2.14 on 2026-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0005_add_state_source_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetaxprofile',
            name='agency_email',
            field=models.CharField(blank=True, default='', help_text='Agency email or contact URL', max_length=200),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='agency_name',
            field=models.CharField(blank=True, default='', help_text='State withholding agency name', max_length=200),
        ),
        migrations.AddField(
            model_name='statetaxprofile',
            name='agency_phone',
            field=models.CharField(blank=True, default='', help_text='Agency phone number(s)', max_length=100),
        ),
    ]
