# Generated by Django 5.2.14 on 2026-07-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0006_statetaxprofile_agency_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(help_text='Locality name (e.g. "NYC", "Yonkers")', max_length=50)),
                ('locality_code', models.CharField(help_text='Short code (e.g. "nyc", "yonkers")', max_length=20)),
                ('filing_status', models.CharField(choices=[('single', 'Single/MFS'), ('married', 'MFJ'), ('head_of_household', 'HOH')], max_length=20)),
                ('min_amount', models.PositiveIntegerField(help_text='Lower bound of bracket (annual)')),
                ('max_amount', models.PositiveIntegerField(blank=True, help_text='Upper bound (null = no limit)', null=True)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Tax rate (e.g. 0.03876 = 3.876%)', max_digits=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_brackets', to='tax_data.statetaxprofile')),
            ],
            options={
                'verbose_name': 'Local Tax Bracket',
                'verbose_name_plural': 'Local Tax Brackets',
                'ordering': ['profile', 'locality_code', 'filing_status', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='LocalTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(help_text='Display name (e.g. "New York City")', max_length=50)),
                ('locality_code', models.CharField(help_text='Short code (e.g. "nyc", "yonkers")', max_length=20)),
                ('tax_type', models.CharField(choices=[('progressive', 'Progressive Brackets'), ('flat', 'Flat Rate'), ('surcharge', 'Surcharge on State Tax')], default='progressive', max_length=12)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Flat rate or surcharge rate (e.g. 0.175 = 17.5% surcharge for Yonkers)', max_digits=6, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description shown to users (e.g. "NYC residents pay additional income tax")')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_taxes', to='tax_data.statetaxprofile')),
            ],
            options={
                'verbose_name': 'Local Tax Info',
                'verbose_name_plural': 'Local Tax Info',
                'ordering': ['profile', 'locality_code'],
                'unique_together': {('profile', 'locality_code')},
            },
        ),
    ]
