# Generated by Django 5.2.14 on 2026-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_data', '0008_localtaxbracket_fk_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaTaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Tax year (e.g. 2026)')),
                ('psd_code', models.CharField(help_text='PA PSD code (e.g. "010201")', max_length=8)),
                ('tax_collection_district', models.CharField(blank=True, default='', max_length=100)),
                ('county', models.CharField(blank=True, default='', max_length=50)),
                ('municipality_id', models.CharField(blank=True, default='', max_length=20)),
                ('municipality', models.CharField(blank=True, default='', max_length=100)),
                ('school_district_id', models.CharField(blank=True, default='', max_length=20)),
                ('school_district', models.CharField(blank=True, default='', max_length=100)),
                ('municipal_nonresident_eit_rate', models.DecimalField(decimal_places=4, default=0, help_text='Municipal nonresident EIT rate (%)', max_digits=7)),
                ('municipal_resident_eit_rate', models.DecimalField(decimal_places=4, default=0, help_text='Municipal resident EIT rate (%)', max_digits=7)),
                ('school_district_eit_rate', models.DecimalField(decimal_places=4, default=0, help_text='School district EIT rate (%)', max_digits=7)),
                ('school_district_pit_rate', models.DecimalField(decimal_places=4, default=0, help_text='School district PIT rate (%)', max_digits=7)),
                ('total_resident_eit_rate', models.DecimalField(decimal_places=4, default=0, help_text='Total resident EIT rate (%)', max_digits=7)),
                ('municipal_eit_lie', models.DecimalField(decimal_places=2, default=0, help_text='Municipal EIT LIE threshold ($)', max_digits=10)),
                ('school_district_eit_lie', models.DecimalField(decimal_places=2, default=0, help_text='School district EIT LIE threshold ($)', max_digits=10)),
                ('municipal_lst', models.DecimalField(decimal_places=2, default=0, help_text='Municipal LST amount ($/year)', max_digits=10)),
                ('school_district_lst', models.DecimalField(decimal_places=2, default=0, help_text='School district LST amount ($/year)', max_digits=10)),
                ('total_lst', models.DecimalField(decimal_places=2, default=0, help_text='Total LST amount ($/year)', max_digits=10)),
                ('municipal_lst_lie', models.DecimalField(decimal_places=2, default=0, help_text='Municipal LST LIE threshold ($)', max_digits=10)),
                ('school_district_lst_lie', models.DecimalField(decimal_places=2, default=0, help_text='School district LST LIE threshold ($)', max_digits=10)),
                ('municipal_lst_effective_date', models.DateField(blank=True, help_text='Date municipal LST rates take effect', null=True)),
                ('school_district_lst_effective_date', models.DateField(blank=True, help_text='Date school district LST rates take effect', null=True)),
                ('eit_collector', models.CharField(blank=True, default='', max_length=200)),
                ('eit_collector_address1', models.CharField(blank=True, default='', max_length=200)),
                ('eit_collector_city', models.CharField(blank=True, default='', max_length=100)),
                ('eit_collector_state', models.CharField(blank=True, default='', max_length=2)),
                ('eit_collector_zip', models.CharField(blank=True, default='', max_length=10)),
                ('eit_collector_phone', models.CharField(blank=True, default='', max_length=50)),
                ('eit_collector_email', models.CharField(blank=True, default='', max_length=200)),
                ('eit_collector_website', models.CharField(blank=True, default='', max_length=300)),
                ('date_last_updated', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PA Tax Code',
                'verbose_name_plural': 'PA Tax Codes',
                'ordering': ['year', 'psd_code'],
                'unique_together': {('year', 'psd_code')},
            },
        ),
    ]
