# Generated by Django 5.2.14 on 2026-06-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_add_dotnet_runtime_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdomain',
            options={'ordering': ['-created_at']},
        ),
    ]
