# Generated by Django 5.2.14 on 2026-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_alter_customdomain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='runtime_kind',
            field=models.CharField(choices=[('static', 'Static'), ('node_static', 'Node Static'), ('node_ssr', 'Node SSR'), ('django', 'Django'), ('dotnet', '.NET'), ('java', 'Java / Spring Boot')], default='static', max_length=20),
        ),
    ]
