# Generated by Django 5.2.14 on 2026-07-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0011_add_java_runtime_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='runtime_kind',
            field=models.CharField(choices=[('static', 'Static'), ('node_static', 'Node Static'), ('node_ssr', 'Node SSR'), ('django', 'Django'), ('dotnet', '.NET'), ('java', 'Java / Spring Boot'), ('android', 'Android (Kotlin)')], default='static', max_length=20),
        ),
    ]
