# Generated by Django 6.0.6 on 2026-07-01 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='repository_selection',
            field=models.CharField(default='all', help_text='all or selected', max_length=50),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='sender_github_id',
            field=models.BigIntegerField(blank=True, help_text='GitHub ID of the user who installed the app', null=True),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='sender_login',
            field=models.CharField(blank=True, help_text='GitHub username of the installer', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubinstallation',
            name='account_name',
            field=models.CharField(help_text='GitHub org or user the app is installed on', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubinstallation',
            name='account_type',
            field=models.CharField(blank=True, help_text='Organization or User', max_length=50),
        ),
        migrations.AlterField(
            model_name='githubinstallation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The SaaSClaw user who installed the GitHub App. Linked via GitHub account ID or username on installation event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstallationRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('repo_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=511)),
                ('private', models.BooleanField(default=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='integrations.githubinstallation')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('installation', 'repo_id')},
            },
        ),
    ]
