# Generated by Django 5.2.14 on 2026-07-18 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_figma_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenpotConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penpot_user_id', models.CharField(blank=True, help_text='Penpot profile ID', max_length=255)),
                ('penpot_email', models.EmailField(max_length=254)),
                ('penpot_password', models.CharField(help_text='Generated random password for Penpot', max_length=255)),
                ('penpot_team_id', models.CharField(blank=True, help_text='Default team ID in Penpot', max_length=255)),
                ('penpot_project_id', models.CharField(blank=True, help_text='Default project ID in Penpot', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penpot_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
